FROM python:3.12.3
WORKDIR /portfolio-app

COPY portfolio-app/app app
COPY portfolio-app/requirements.txt portfolio-app/config.py  portfolio-app/.flaskenv portfolio-app/.env-dev portfolio-app/.env-standalone portfolio-app/run.py ./
RUN pip install -r ./requirements.txt
RUN pip install gunicorn
ENV FLASK_DEBUG False

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "run:app"]
