FROM python:3.12.3
WORKDIR /todo-app

COPY todo-app/app app
COPY todo-app/requirements.txt todo-app/config.py  todo-app/.flaskenv todo-app/.env-dev todo-app/.env-standalone todo-app/run.py ./
RUN pip install -r ./requirements.txt
RUN pip install gunicorn
ENV FLASK_DEBUG False

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "run:app"]
