FROM python:3.12.3
WORKDIR /event-app

COPY event-app/app app
COPY event-app/requirements.txt event-app/config.py  event-app/.flaskenv event-app/.env-dev event-app/.env-standalone event-app/run.py ./
RUN pip install -r ./requirements.txt
RUN pip install gunicorn
ENV FLASK_DEBUG False

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "run:app"]
